import pandas as pd
melb_data = pd.read_csv('project 2\data\melb_data.csv', sep=',')
melb_data['Car'] = melb_data['Car'].astype('int64')
melb_data['Bedroom'] = melb_data['Bedroom'].astype('int64')
melb_data['Bathroom'] = melb_data['Bathroom'].astype('int64')
melb_data['Propertycount'] = melb_data['Propertycount'].astype('int64')
melb_data['YearBuilt'] = melb_data['YearBuilt'].astype('int64')
melb_data.info()
print(melb_data.describe().loc[:,['BuildingArea']])
print(melb_data.describe(include=['object']))
print(melb_data['Type'].value_counts(normalize=True))