import pandas as pd

ratings1 = pd.read_csv('project 4\data\\ratings1.csv')
ratings2 = pd.read_csv('project 4\data\\ratings2.csv')
dates = pd.read_csv('project 4\data\dates.csv')
movies = pd.read_csv('project 4\data\movies.csv')
ratings = pd.concat([ratings1, ratings2], ignore_index=True)
print(ratings)
ratings = ratings.drop_duplicates(ignore_index=True)
print('Число строк в таблице ratings: ', ratings.shape[0])
print('Число строк в таблице ratings: ', ratings.shape[0])
print('Число строк в таблице dates: ', dates.shape[0])
print(ratings.shape[0] == dates.shape[0])
ratings_dates = pd.concat([ratings, dates], axis=1)
print(ratings_dates.tail(7))